### ISSUE TITLE
Definir bien la idea del objetivo

### ISSUE THREAD

**Issue by d0387** [cuba-weather/cuba-weather.github.io#10]
Es objetivo nuestro que desde cualquier plataforma se pueda disfrutar de nuestra aplicación y se está trabajando en eso. **En un principio nos enfocaremos en Android, iOS, Web, Windows y Linux principalmente, por ser los más usados**. Actualmente está disponible la versión para Android desde Apklis.

Prácticamente dice que en un principio se enfocarán en todos los sistemas operativos y estoy seguro que la idea es resaltar una pareja de SO por ser los más usados

**Comment by leynier** [comment]
Edite la descripción, ahora no menciono la lista de plataformas, solo que se desea estar presente en todas las plataformas.
